exports.events = [
  {
    id: '6c0244cd-7cf7-4869-be81-cfd1d24de143',
    title: 'registration',
    date: '2021-06-23',
    time: '9.00-11.00',
    location: 'canteen ',
    teacher: '',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in nulla porttitor neque pretium hendrerit id vitae diam. Sed eget odio vel mi tempor tincidunt sed in tellus.',
    tag: '',
    prerequisites: '',
  },
  {
    id: 'b2612b42-0db4-472b-a2f4-3500813891b9',
    title: 'warm up',
    date: '2021-06-23',
    time: '10.00-10.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Praesent sed nisi et tellus elementum pulvinar. Vestibulum non vestibulum felis. Praesent ligula elit, placerat sit amet eleifend aliquet, viverra eu mi. Pellentesque ornare accumsan dignissim. Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit. ',
    tag: 'all levels',
    prerequisites: '',
  },
  {
    id: '40b34f2d-6118-43ad-b16f-2e05788395cd',
    title: 'workshop 1',
    date: '2021-06-23',
    time: '11.00-12.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Vivamus sagittis quis tortor et convallis. Donec cursus eros elit, ut aliquet mauris sollicitudin ut. Nam blandit quam et nisi sagittis euismod. Nulla tempor accumsan imperdiet. ',
    tag: 'begginers',
    prerequisites: 'lectus, tellus',
  },
  {
    id: 'a45b326a-ff43-4abb-816f-6e6d6a404e5d',
    title: 'workshop 2',
    date: '2021-06-23',
    time: '11.00-12.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Vivamus sagittis quis tortor et convallis. Donec cursus eros elit, ut aliquet mauris sollicitudin ut. Nam blandit quam et nisi sagittis euismod. Nulla tempor accumsan imperdiet. ',
    tag: 'intermediate',
    prerequisites: 'lectus, tellus',
  },
  {
    id: '64443716-1ab8-46ab-a81d-1d09e2353ed2',
    title: 'workshop 3',
    date: '2021-06-23',
    time: '11.00-12.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'advanced',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: '769b2d7a-7501-4499-b9da-e5530c023297',
    title: 'workshop 4',
    date: '2021-06-23',
    time: '12.30-13.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'all levels',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: 'be655999-0fb5-46fd-8d1b-e8a1f0268179',
    title: 'workshop 5',
    date: '2021-06-23',
    time: '12.30-13.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'intermediate',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: '77d8abcd-e96e-431c-ac5c-35cd7e62184c',
    title: 'workshop 6',
    date: '2021-06-23',
    time: '12.30-13.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'begginers',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: '8c2f3315-2e35-43b0-90ab-4f8ac80f0403',
    title: 'workshop 7',
    date: '2021-06-23',
    time: '12.30-13.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'advanced',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: 'd5c48e40-5381-4ac3-8620-8810104fdc54',
    title: 'lunch',
    date: '2021-06-23',
    time: '14.00-15.30',
    location: 'canteen',
    teacher: '',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in nulla porttitor neque pretium hendrerit id vitae diam. Sed eget odio vel mi tempor tincidunt sed in tellus.',
    tag: '',
    prerequisites: '',
  },
  {
    id: 'afb94826-b449-4a91-a2c5-1a2b5dbf4653',
    title: 'workshop 8',
    date: '2021-06-23',
    time: '16.00-17.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Praesent sed nisi et tellus elementum pulvinar. Vestibulum non vestibulum felis. Praesent ligula elit, placerat sit amet eleifend aliquet, viverra eu mi. Pellentesque ornare accumsan dignissim. Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit. ',
    tag: 'intermediate',
    prerequisites: 'lorem, ipsum',
  },
  {
    id: '921e0c0e-b2f0-443e-b512-1240d49d15ee',
    title: 'workshop 9',
    date: '2021-06-23',
    time: '16.00-17.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Vivamus sagittis quis tortor et convallis. Donec cursus eros elit, ut aliquet mauris sollicitudin ut. Nam blandit quam et nisi sagittis euismod. Nulla tempor accumsan imperdiet. ',
    tag: 'advanced',
    prerequisites: 'lectus, tellus',
  },
  {
    id: '22b94130-b407-4399-9056-03d058fb0a7e',
    title: 'workshop 10',
    date: '2021-06-23',
    time: '16.00-17.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Vivamus sagittis quis tortor et convallis. Donec cursus eros elit, ut aliquet mauris sollicitudin ut. Nam blandit quam et nisi sagittis euismod. Nulla tempor accumsan imperdiet. ',
    tag: 'advanced',
    prerequisites: 'lectus, tellus',
  },
  {
    id: 'a9d6eafb-39be-4afa-bf27-53141303a405',
    title: 'dinner',
    date: '2021-06-23',
    time: '17.30-19.00',
    location: 'canteen',
    teacher: '',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in nulla porttitor neque pretium hendrerit id vitae diam. Sed eget odio vel mi tempor tincidunt sed in tellus. Ut ut ipsum eget libero blandit luctus eget vel ipsum. Cras et diam interdum, tincidunt ipsum eget, lobortis ex.',
    tag: '',
    prerequisites: '',
  },
  {
    id: 'bbe2deca-f937-42fe-a53a-f624352842d8',
    title: 'yoga',
    date: '2021-06-24',
    time: '7.00-8.00',
    location: 'main hall ',
    teacher: '',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in nulla porttitor neque pretium hendrerit id vitae diam. Sed eget odio vel mi tempor tincidunt sed in tellus.',
    tag: 'all levels',
    prerequisites: '',
  },
  {
    id: 'd0af50b1-72f6-4f1e-96f4-07fd20549ba5',
    title: 'breakfast',
    date: '2021-06-24',
    time: '8.00-9.30',
    location: 'canteen ',
    teacher: '',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in nulla porttitor neque pretium hendrerit id vitae diam. Sed eget odio vel mi tempor tincidunt sed in tellus.',
    tag: '',
    prerequisites: '',
  },
  {
    id: '7c17cec2-bdcb-4931-a485-f459813ad255',
    title: 'warm up',
    date: '2021-06-24',
    time: '10.00-10.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Praesent sed nisi et tellus elementum pulvinar. Vestibulum non vestibulum felis. Praesent ligula elit, placerat sit amet eleifend aliquet, viverra eu mi. Pellentesque ornare accumsan dignissim. Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit. ',
    tag: 'all levels',
    prerequisites: '',
  },
  {
    id: '510e4e34-9723-4821-ac33-52504aa87af8',
    title: 'workshop 11',
    date: '2021-06-24',
    time: '11.00-12.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Vivamus sagittis quis tortor et convallis. Donec cursus eros elit, ut aliquet mauris sollicitudin ut. Nam blandit quam et nisi sagittis euismod. Nulla tempor accumsan imperdiet. ',
    tag: 'begginers',
    prerequisites: 'lectus, tellus',
  },
  {
    id: '96545612-a50f-4420-be39-e90570dc8836',
    title: 'workshop 12',
    date: '2021-06-24',
    time: '11.00-12.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Vivamus sagittis quis tortor et convallis. Donec cursus eros elit, ut aliquet mauris sollicitudin ut. Nam blandit quam et nisi sagittis euismod. Nulla tempor accumsan imperdiet. ',
    tag: 'intermediate',
    prerequisites: 'lectus, tellus',
  },
  {
    id: 'a5c1ed4c-8785-416f-a619-f32fab020d87',
    title: 'workshop 13',
    date: '2021-06-24',
    time: '11.00-12.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'advanced',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: 'a3894b48-d5b8-4c31-a33a-8d845e991a16',
    title: 'workshop 14',
    date: '2021-06-24',
    time: '12.30-13.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'all levels',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: '03005ee1-5fb1-4a6f-8273-4d856ce56ccb',
    title: 'workshop 15',
    date: '2021-06-24',
    time: '12.30-13.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'intermediate',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: '5921e78f-d806-4d9a-8499-654eefcf90b2',
    title: 'workshop 16',
    date: '2021-06-24',
    time: '12.30-13.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'begginers',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: '73e48cac-9fbc-4bd2-8737-1063e5c5993b',
    title: 'workshop 17',
    date: '2021-06-24',
    time: '12.30-13.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'advanced',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: 'b57ca4e6-4191-40ca-9b8f-1e3ecc70defe',
    title: 'lunch',
    date: '2021-06-24',
    time: '14.00-15.30',
    location: 'canteen',
    teacher: '',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in nulla porttitor neque pretium hendrerit id vitae diam. Sed eget odio vel mi tempor tincidunt sed in tellus.',
    tag: '',
    prerequisites: '',
  },
  {
    id: 'f130493c-f964-409b-8e81-5acb37fbd6d5',
    title: 'workshop 18',
    date: '2021-06-24',
    time: '16.00-17.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Praesent sed nisi et tellus elementum pulvinar. Vestibulum non vestibulum felis. Praesent ligula elit, placerat sit amet eleifend aliquet, viverra eu mi. Pellentesque ornare accumsan dignissim. Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit. ',
    tag: 'intermediate',
    prerequisites: 'lorem, ipsum',
  },
  {
    id: 'f35b7696-98ae-4750-bb0c-85e716bd9d94',
    title: 'workshop 19',
    date: '2021-06-24',
    time: '16.00-17.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Vivamus sagittis quis tortor et convallis. Donec cursus eros elit, ut aliquet mauris sollicitudin ut. Nam blandit quam et nisi sagittis euismod. Nulla tempor accumsan imperdiet. ',
    tag: 'advanced',
    prerequisites: 'lectus, tellus',
  },
  {
    id: '7536a7b1-e0a3-43c0-b488-a3e53d6fdecf',
    title: 'workshop 20',
    date: '2021-06-24',
    time: '16.00-17.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Vivamus sagittis quis tortor et convallis. Donec cursus eros elit, ut aliquet mauris sollicitudin ut. Nam blandit quam et nisi sagittis euismod. Nulla tempor accumsan imperdiet. ',
    tag: 'advanced',
    prerequisites: 'lectus, tellus',
  },
  {
    id: '22f952c1-47ab-4804-85af-c8b07cbdfe02',
    title: 'dinner',
    date: '2021-06-24',
    time: '17.30-19.00',
    location: 'canteen',
    teacher: '',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in nulla porttitor neque pretium hendrerit id vitae diam. Sed eget odio vel mi tempor tincidunt sed in tellus. Ut ut ipsum eget libero blandit luctus eget vel ipsum. Cras et diam interdum, tincidunt ipsum eget, lobortis ex.',
    tag: '',
    prerequisites: '',
  },
  {
    id: '55ef2a14-2d0c-4273-814c-272db21f9a70',
    title: 'yoga',
    date: '2021-06-25',
    time: '7.00-8.00',
    location: 'main hall ',
    teacher: '',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in nulla porttitor neque pretium hendrerit id vitae diam. Sed eget odio vel mi tempor tincidunt sed in tellus.',
    tag: 'all levels',
    prerequisites: '',
  },
  {
    id: 'c3d20310-183d-4396-a811-cc008ea2461c',
    title: 'breakfast',
    date: '2021-06-25',
    time: '8.00-9.30',
    location: 'canteen ',
    teacher: '',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in nulla porttitor neque pretium hendrerit id vitae diam. Sed eget odio vel mi tempor tincidunt sed in tellus.',
    tag: '',
    prerequisites: '',
  },
  {
    id: 'b09065fa-56cf-4b0a-926d-e9bb9ed1cea2',
    title: 'warm up',
    date: '2021-06-25',
    time: '10.00-10.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Praesent sed nisi et tellus elementum pulvinar. Vestibulum non vestibulum felis. Praesent ligula elit, placerat sit amet eleifend aliquet, viverra eu mi. Pellentesque ornare accumsan dignissim. Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit. ',
    tag: 'all levels',
    prerequisites: '',
  },
  {
    id: 'a76692c8-7ce9-449e-a2fd-751bfc8c09c0',
    title: 'workshop 21',
    date: '2021-06-25',
    time: '11.00-12.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Vivamus sagittis quis tortor et convallis. Donec cursus eros elit, ut aliquet mauris sollicitudin ut. Nam blandit quam et nisi sagittis euismod. Nulla tempor accumsan imperdiet. ',
    tag: 'begginers',
    prerequisites: 'lectus, tellus',
  },
  {
    id: 'f6c12fd5-474d-4a15-a08c-b0a9ca2da22f',
    title: 'workshop 22',
    date: '2021-06-25',
    time: '11.00-12.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Vivamus sagittis quis tortor et convallis. Donec cursus eros elit, ut aliquet mauris sollicitudin ut. Nam blandit quam et nisi sagittis euismod. Nulla tempor accumsan imperdiet. ',
    tag: 'intermediate',
    prerequisites: 'lectus, tellus',
  },
  {
    id: 'e81a9dea-8a7e-436d-901a-0e33be74c78f',
    title: 'workshop 23',
    date: '2021-06-25',
    time: '11.00-12.00',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'advanced',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: '60243b2a-8711-4a9e-9448-eca0264abd9a',
    title: 'workshop 24',
    date: '2021-06-25',
    time: '12.30-13.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'all levels',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: '8ac73f31-dcb6-4471-8fb9-48f826f5ca64',
    title: 'workshop 25',
    date: '2021-06-25',
    time: '12.30-13.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'intermediate',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: '4417fadf-5b10-4baa-bfe0-20c481542f90',
    title: 'workshop 26',
    date: '2021-06-25',
    time: '12.30-13.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'begginers',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: '2b5fafff-ae5a-43db-a949-9a9f12446c1d',
    title: 'workshop 27',
    date: '2021-06-25',
    time: '12.30-13.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit.',
    tag: 'advanced',
    prerequisites: 'tellus, ipsum',
  },
  {
    id: '5a891ddc-3423-42d5-8683-6316fe637a55',
    title: 'lunch',
    date: '2021-06-25',
    time: '14.00-15.30',
    location: 'canteen',
    teacher: '',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in nulla porttitor neque pretium hendrerit id vitae diam. Sed eget odio vel mi tempor tincidunt sed in tellus.',
    tag: '',
    prerequisites: '',
  },
  {
    id: 'daca58d3-763c-4742-83fd-30816d5bf881',
    title: 'clean up',
    date: '2021-06-25',
    time: '15.30-16.30',
    location: 'main hall',
    teacher: 'name surname',
    description:
      'Praesent sed nisi et tellus elementum pulvinar. Vestibulum non vestibulum felis. Praesent ligula elit, placerat sit amet eleifend aliquet, viverra eu mi. Pellentesque ornare accumsan dignissim. Mauris mattis magna a lectus iaculis, nec pulvinar lectus tristique. Curabitur molestie nisi sed aliquam suscipit. ',
    tag: '',
    prerequisites: '',
  },
];

exports.config = {
  title: 'Polish festival',
  tagTitle: 'level',
  tagsTitle: 'levels',
};

exports.tags = [
  {
    name: 'begginers',
    color: '#06D6A0',
  },
  {
    name: 'intermediate',
    color: '#FFD166',
  },
  {
    name: 'advanced',
    color: '#EF476F',
  },
  {
    name: 'all levels',
    color: '#118AB2',
  },
];
